apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetwebapp
  labels:
    app: dotnetwebapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnetwebapp
  template:
    metadata:
      labels:
        app: dotnetwebapp
    spec:
      containers:
        env:
          - name: AWS_ACCOUNT_ID
            valueFrom:
              secretKeyRef:
                name: aws-account-id         # Secret Name
                key: AWS_ACCOUNT_ID          # Key inside the Secret
          - name: ECR_REPOSITORY
            valueFrom:
              secretKeyRef:
                name: ecr-repository         # Secret Name
                key: ECR_REPOSITORY          # Key inside the Secret
      - name: dotnetwebapp
        image: "${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/$(ECR_REPOSITORY):latest"
        ports:
        - containerPort: 80

