apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetwebapp
  labels:
    app: dotnetwebapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnetwebapp
  template:
    metadata:
      labels:
        app: dotnetwebapp
    spec:
      containers:
      - name: dotnetwebapp
        image: 248189926503.dkr.ecr.us-east-1.amazonaws.com/dotnetwebapp:latest
        ports:
        - containerPort: 80

