apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetwebapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnetwebapp
  template:
    metadata:
      labels:
        app: dotnetwebapp
    spec:
      containers:
        - name: dotnetwebapp
          image: ${{ secrets.AWS_ECR_URL }}/dotnetwebapp:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dotnetwebapp-service
spec:
  selector:
    app: dotnetwebapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

